### ISSUE TITLE
Eslint fails

### ISSUE THREAD

**Issue by aminya** [atom-community/atom-ide-base#56]
```js
> eslint .


Oops! Something went wrong! :(

ESLint: 7.19.0

TypeError: state.popChainContext is not a function
Occurred while linting C:\Users\aminy\atom-ide\nuclide\nuclide-commons\fsPromise.js:345
    at processCodePathToExit (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:512:19)
    at CodePathAnalyzer.leaveNode (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:729:9)
    at CodePathAnalyzer.overrideLeaveNode (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint-plugin-node@11.1.0_eslint@7.19.0\node_modules\eslint-plugin-node\lib\rules\process-exit-as-throw.js:130:27)
    at C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\linter\linter.js:954:32
    at Array.forEach (<anonymous>:null:null)
    at runRules (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\linter\linter.js:947:15)
    at Linter._verifyWithoutProcessors (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\linter\linter.js:1173:31)
    at Linter._verifyWithConfigArray (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\linter\linter.js:1271:21)
    at Linter.verify (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\linter\linter.js:1226:25)
    at LinterPrototype.verify (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint-plugin-only-warn@1.0.2\node_modules\eslint-plugin-only-warn\src\only-warn.js:14:55)
    at Linter.verifyAndFix (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\linter\linter.js:1416:29)
    at verifyText (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\cli-engine\cli-engine.js:239:48)
    at CLIEngine.executeOnFiles (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\cli-engine\cli-engine.js:807:28)
    at ESLint.lintFiles (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\eslint\eslint.js:521:23)
    at Object.execute (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\lib\cli.js:294:36)
    at main (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\bin\eslint.js:142:52)
    at Object.<anonymous> (C:\Users\aminy\atom-ide\node_modules\.pnpm\eslint@7.19.0\node_modules\eslint\bin\eslint.js:146:2)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

```

**Tell us about your environment**

* **ESLint Version:** 7.19.0
* **Node Version:** 15.8.0
* **npm Version:** 6.14.11

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** 

I am using [eslint-config-atomic](https://github.com/atom-community/eslint-config-atomic/)

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "extends": "eslint-config-atomic",
  "ignorePatterns": ["dist/", "node_modules/"]
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

https://github.com/atom-community/atom-ide-base/blob/8e952b465a6485eee76881cc201108e5bd853668/nuclide/nuclide-commons/fsPromise.js#L345
```js
const mode = typeof options !== 'string' ? options?.mode : null;
```

```bash
eslint .
```

**What did you expect to happen?**
Lint

**What actually happened? Please include the actual, raw output from ESLint.**
An internal Eslint error happens

**Are you willing to submit a pull request to fix this bug?**
Not sure how to fix it

Mirror: https://github.com/atom-community/atom-ide-base/issues/56

**Comment by aminya** [comment]
This should become an Eslint issue.
