### ISSUE TITLE
Failed to activate the atom-ide-base package

### ISSUE THREAD

**Issue by Estebanmartinac** [atom-community/atom-ide-base#91]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-base](https://github.com/atom-community/atom-ide-base) package 3.4.0

### Stack Trace

Failed to activate the atom-ide-base package

```
At Invalid or unexpected token

C:\Users\57317\.atom\packages\atom-ide-base\package\main.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { 
                                                                                                                                                           

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:84:7)
    at NativeCompileCache.runInThisContext (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:148814)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149668)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508497)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:386056)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:384807
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-ide-base 3.4.0 
atom-python-test 1.0.1 
atom-runner 2.7.1 
autocomplete-java 1.2.7 
basic-java-compile 0.4.0 
ide-python 1.9.7 
java-class-complete 0.0.6 
python-debugger 0.2.0 
python-docstring 0.0.3 
run-python-simply 0.6.0 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall atom-ide-base
```
Clear your cache then

```
apm install atom-ide-base
```

https://github.com/atom/apm/issues/919
